version: '3.8'

services:
  myapp:
    build:
      context: ./shop-backend
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_IMAGE_BUCKET: ${AWS_IMAGE_BUCKET}
      AWS_IMAGE_HOST: ${AWS_IMAGE_HOST}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: myapp-postgres
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      LISTEN_IP: 0.0.0.0
      LISTEN_PORT: 8160
    depends_on:
      myapp-postgres:
        condition: service_healthy
    ports:
      - "8160:8160"

  myapp-postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
    volumes:
      - ./deploy/postgres/data:/var/lib/postgresql/data:z
